{
 "title": "Tripwire",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "strategy", "label": "Strategy", "query": { "query": "label_values(strategy)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "The rate of requests being sent from clients.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(client_req_total{strategy=\"$strategy\"}[$__rate_interval]))",
     "legendFormat": "Actual"
    },
    {
     "expr": "rate_limit{strategy=\"adaptivelimiter\"} > 0",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "Read the panels from the top down.\n\n- The Requests panel shows the rate of requests being sent to the server.\n- The Queueing panel shows requests that are blocked waiting to be processed.\n- The Concurrency panel shows inflight requests that are currently being processed.\n- The Response Times panel indicates what the latency of responses is at clients.\n- The Responses panel indicates what the result of the requests was.\n- The Load Shedding panel indicates when requests are being pre-emptively rejected."
   }
  },
  {
   "title": "Queueing",
   "type": "timeseries",
   "description": "Requests that are blocked waiting to be processed.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "queued_requests{strategy=\"$strategy\"}",
     "legendFormat": "Blocked Requests"
    }
   ]
  },
  {
   "title": "Runs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "client_req_successes / client_req_total",
     "legendFormat": "Success rate"
    },
    {
     "expr": "histogram_sum(client_req_response_times) / histogram_count(client_req_response_times)",
     "legendFormat": "Avg response time"
    },
    {
     "expr": "client_req_successes / client_req_total # Score = Success Rate * Duration / sqrt(Avg Latency). This is meant to give more weight to success rate than latency\n* run_duration\n/ sqrt((histogram_sum(client_req_response_times) / histogram_count(client_req_response_times)))",
     "legendFormat": "Score"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "description": "Inflight requests that are currently being processed",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "server_inflight_requests{strategy=\"$strategy\"}",
     "legendFormat": "Inflight"
    },
    { "expr": "server_threads", "legendFormat": "Capacity" },
    {
     "expr": "concurrency_limit{strategy=\"$strategy\"} > 0",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "description": "The response times measured by clients.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(histogram_sum(rate(client_req_response_times{strategy=\"$strategy\"}[$__rate_interval]))) \n/ \nsum(histogram_count(rate(client_req_response_times{strategy=\"$strategy\"}[$__rate_interval]))) # Sum to get rid of run_id label",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(client_req_response_times{strategy=\"$strategy\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(.9, sum(rate(client_req_response_times{strategy=\"$strategy\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(.99, sum(rate(client_req_latency{strategy=\"$strategy\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "min_timeout{strategy=\"$strategy\"} > 0",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "description": "The result of requests.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(client_req_successes{strategy=\"$strategy\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(irate(client_req_rejected{strategy=\"$strategy\"}[$__rate_interval]))",
     "legendFormat": "Rejected"
    },
    {
     "expr": "sum(irate(client_req_timeouts{strategy=\"$strategy\"}[$__rate_interval]))",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Load Shedding",
   "type": "timeseries",
   "description": "The probability that requests are being rejected.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "throttle_probability{strategy=\"$strategy\"}",
     "legendFormat": "Throttle Probability"
    }
   ]
  }
 ]
}