# Compares the Failsafe-go adaptive limiter to the go-concurrency-limits limiters.

client:
  workloads:
    - name: writes
      rps: 100
      service_times:
        - service_time: 50ms

server:
  threads: 12

strategies:
  - name: adaptivelimiter
    client_policies:
      - adaptivelimiter:
          short_window_min_duration: 1s
          short_window_max_duration: 1s
          short_window_min_samples: 10
          long_window_size: 60
          min_limit: 2
          max_limit: 150
          initial_limit: 20
          max_limit_factor: 5
          correlation_window_size: 20
          initial_rejection_factor: 2
          max_rejection_factor: 3