# Demonstrates a Failsafe-go adaptive throttler, using workloads that can be adjusted via the REST API

client:
  workloads:
    - name: writes
      rps: 100
      service_times:
        - service_time: 150ms

server:
  threads: 12

strategies:
  - name: client adaptivethrottler and timeout
    client_policies:
      - adaptivethrottler:
          failure_rate_threshold: .1
          thresholding_period: 30s
          max_rejection_rate: .9
      # Timeouts are used to drive the adaptivethrottler
      - timeout: 5s