# Demonstrates and compares limiters from the go-concurrency-limits library
# https://github.com/platinummonkey/go-concurrency-limits

client:
  stages:
    - duration: 20s
      rps: 100
      service_times:
        - service_time: 50ms
    - duration: 40s
      service_times:
        - service_time: 150ms
    - duration: 20s
      service_times:
        - service_time: 50ms

server:
  threads: 12

strategies:
  - name: vegaslimiter
    client_policies:
      - vegaslimiter:
          max_limit: 150
          initial_limit: 20
          recent_window_min_duration: 1s
          recent_window_max_duration: 1s
          recent_window_min_samples: 10
          smoothing_factor: .1

  - name: gradientlimiter
    client_policies:
      - gradientlimiter:
          min_limit: 2
          max_limit: 150
          initial_limit: 20
          recent_window_min_duration: 1s
          recent_window_max_duration: 1s
          recent_window_min_samples: 10
          smoothing_factor: .1

  - name: gradient2limiter
    client_policies:
      - gradient2limiter:
          min_limit: 2
          max_limit: 150
          initial_limit: 20
          recent_window_min_duration: 1s
          recent_window_max_duration: 1s
          recent_window_min_samples: 10
          baseline_window_age: 60
          smoothing_factor: .1
