# Demonstrates the runaway limits problem with a go-concurrency-limits limiter.
# The runaway limits problem is where the limit gradually increases, indefinitely, even though the system is overloaded.
# This happens when the baseline/longRTT adjusts upwards too fast, causing the baseline to gradually increase.
# This problem is something the Failsafe-go adaptive limiter avoids.
#
# https://github.com/platinummonkey/go-concurrency-limits

client:
  workloads:
    - name: writes
      rps: 100
      service_times:
        - service_time: 120ms # This should be set to just enough to cause overload on your machine

server:
  threads: 12

strategies:
  - name: gradient2limiter
    client_policies:
      - gradient2limiter:
          min_limit: 2
          max_limit: 150
          initial_limit: 20
          recent_window_min_duration: 1s
          recent_window_max_duration: 1s
          recent_window_min_samples: 10
          baseline_window_age: 60
          smoothing_factor: .1
